src/nw_notification_manager_linux.cc
This allows node-webkit to be built on CentOS (see issues #684, #1966).
=> Add version check for libnotify.

.gitignore, README.md
The links to release notes for the downloads section were going to the old group, which does not exist. This showed a 404 error.
=> updated release notes links to new group

src/net/shell_url_request_context_getter.cc
HTTP cache randomly crashes on exiting NW on Windows. Switching the cache backend from `CACHE_BACKEND_SIMPLE` to `CACHE_BACKEND_DEFAULT` fixes this issue.
=> Fix random http cache crash on Windows

src/shell_browser_main_parts.cc
The fix is a workaround for rogerwang/node-webkit#2206.
=> Set default port of devtools to 9222

src/shell_devtools_frontend.cc, src/shell_devtools_frontend.h
When frontend host is registered for devtools, "inspectedURLChanged" message is sent to frontend host when devtools is loaded. This fix handles the message and resets the title to show current inspected page.
=> Fixed title for devtools

src/browser/file_select_helper.cc
The owning window is not properly get on Windows platform, so that file dialog does not block the parent window correctly.
=> Make file dialog modal on Windows

tests/manual_tests/custom_tray_menu/index.html
Set `'visible-on-all-workspaces'` to `true` so the custom tray menu is displayed on all workspaces.
As @FWeinb suggested in https://github.com/rogerwang/node-webkit/pull/2799#issuecomment-67094763
=> Update test case accounting for multiple workspaces

nw.gypi, src/api/screen/desktop_capture_api.cc, src/api/screen/desktop_capture_api.h, src/api/screen/screen.cc, src/api/screen/screen.js, src/nw_shell.cc, src/nw_shell.h
Chrome Screen Selection does not work ubuntu linux
hence I am not yet supporting it on linux
how to use it:
var gui = require('nw.gui');
gui.Screen.Init();
gui.Screen.chooseDesktopMedia(["window","screen"], 
function(streamId) {
var vid_cons = {mandatory: {chromeMediaSource: 'desktop', chromeMediaSourceId: streamId, maxWidth: 1920, maxHeight: 1080}, optional:[]};
navigator.webkitGetUserMedia({audio: false, video: vid_cons}, success_func, fallback_func);
});
=> [Screen Selection] OSX and Win implementation

src/api/clipboard/clipboard.js, src/api/menu/menu.js, src/api/menuitem/menuitem.js, src/api/screen/screen.js, src/api/shortcut/shorcut.js, src/api/tray/tray.js, src/api/window_bindings.js
Although in JavaScript anything can be thrown, it's much better to throw Errors, not just Strings. It's more semantic and debugger-friendly.
=> Use only instances of Error in throw statement

src/nw_notification_manager_linux.cc
If this looks familiar, it's the same as my old #2818 PR for CentOS 6 support, but that got left behind when the nw12 branch became the new master. I've rebased it on the new master.
Let me know if this should be merged into the nw12 branch instead.
=> Check for libnotify API version

src/browser/shell_devtools_manager_delegate.cc
ShellDevToolsDelegate::GetDiscoveryPageHTML should load resource bundle from
IDR_NW_DEVTOOLS_DISCOVERY_PAGE other than IDR_CONTENT_SHELL_DEVTOOLS_DISCOVERY_PAGE
=> Fix #3143: remote debugging devtools page blank

src/api/app/app.js
Currently regexps are too greedy and can erroneously filter out command line args that aren't nw.js keys. For example, `--my--url=…` and `final--no-toolbar.png`.
Also, trailing “match-anything” `.*` were removed as it doesn't affect the `Regexp::test` behavior.
=> More precise RegExp for App.argv filtering

README.md
App-name did not match in readme + removed comment from code-block.
=> Correct Mac OS X example app name

README.md
Countering the error: "Please make sure that your project's package.json includes a
version and a name value" while starting with `nwbuild -r .`.
=> Added mandatory version to package.json example in README.md.

src/resources/api_nw_shortcut.js
@rogerwang I used a wrong separator in last PR. This changes it to right one.
=> Fixed nw.Shortcut separator

src/api/_api_features.json, src/api/nw_object.idl, src/api/nw_object_api.cc, src/api/nw_object_api.h, src/resources/api_nw_menu.js, src/resources/api_nw_object.js, src/resources/api_nw_tray.js
On Mac, `nw.Object` is overwritten by global `Object` object. Since `nw` holds all globals of Node context, I suggest to rename `nw.Object` to `nw.Obj` to avoid conflict with global variables.
=> Renamed `nw.Object` to `nw.Obj` to avoid conflict

docs/References/Manifest Format.md, src/nw_content.cc, test/remoting/node-remote-array/http-server.py, test/remoting/node-remote-array/index.html, test/remoting/node-remote-array/test.py
`node-remote` can accept string or array of matched patterns, like `['https://*.google.com/*', 'https://*.github.com/*']`.
=> Accept array of matched patterns in `node-remote`

src/resources/api_nw_window.js
=> Reversed `x` and `y` in `win.moveTo` and `win.moveBy`

LICENSE
Fix outdated copyright year (updated to 2016).
The copyright year was out of date. Copyright notices must reflect the current year, so this commit updates the listed year to 2016.
See http://www.copyright.gov/circs/circ01.pdf for more info.
=> Updated year in licence

src/nw_content.cc
In separate mode, the Node context is created within the context of
background page. Overwrite the debugger id will cause debugger filter
out the compiled scripts from Node.
Fixed #4121
=> Remove debugger id index for Node

test/remoting/win-move/index.html, test/remoting/win-move/package.json, test/remoting/win-move/test.py
related to issue #4136 
This case is skipped for Linux because of an upstream issue. See #4217 .
=> test case for `win.move()`

README.md
There is no link to the docs in the repo, I thought it would be useful to add it.
=> Add official docs link to Readme

test/remoting/issue4007-reload-lost-app-window/index.html, test/remoting/issue4007-reload-lost-app-window/package.json, test/remoting/issue4007-reload-lost-app-window/test.py
This test case will be skipped for Mac due to #4165
=> test case for issue #4007

test/remoting/issue4118-mac-quit/test.py
Sometimes hotkey was sent too fast so that system doesn't know it. Adding a small interval (0.1s) between each keys.
=> Added a small interval for triggering hotkey

tools/package_binaries.py
`dbghelp.dll` is required to run on Win XP. Added it to package
script.
Fixed #4181
=> Fix package script for supporting Win XP

test/remoting/issue4269-click-link-crash/http-server.py, test/remoting/issue4269-click-link-crash/inspect.tpl, test/remoting/issue4269-click-link-crash/test.py
@rogerwang Previous test case may timeout because trying to open external site https://www.google.com/. This patch replace it with a temp local site.
=> Not open external site for case #4269

docs/For Users/Getting Started.md
`Simpley` → `Simply`
`reditribute` → `redistribute`
=> Fix typos in User getting started guide

docs/For Users/Getting Started.md
Drag & Drop on Windows works with folder containing `package.json` not file itself
=> Update Getting Started.md

docs/For Users/Package and Distribute.md
Consistent naming `nw-builder` instead of old `node-webkit-builder`
=> Update Package and Distribute.md

src/browser/menubar_controller.cc, src/browser/menubar_controller.h
When pressing a menubar button and navigate to another, such as
clicking `File` and navigate to `Edit`, `MenuModelAdapter` will
still try to find buttons within the model which it was created
with, which is `File` in this case. The fix is to record current
active model and override two `ExecuteCommand` methods to find
buttons in the correct model.
Fixed #4371
=> Fix of not finding menubar button when navigate to another menu

test/remoting/issue3780-jailed/test.py, test/remoting/issue3835-inspect-crash/test.py
DevTools on CR49 doesn't auto focus on the console input fields, which fails two test cases depends on the behaviour.
=> Fixed devtools tests failure on CR49

docs/For Users/Migration/From 0.12 to 0.13.md, docs/References/Screen.md, src/api/nw_screen.idl, src/api/nw_screen_api.cc, src/api/nw_screen_api.h, src/resources/api_nw_screen.js
Media source id returned by `added` event should be registered
before using with `getUserMedia()`. Media source id, e.g.
"screen:0", is permanent until removed, while registered stream id
is a temporary one-time random string accessible only from the
frame that requesting it.
Fixed #4459
=> Added `registerStream()` for using stream id in `getUserMedia()`

test/remoting/issue4221-win-open-manifest/index.html
Size used in NW.js app is the content (inner) size. Fix for test
case #4221.
Previously it was tested on Linux which wrongly reports the same value of `outerWidth` and `innerWidth` due to upstream issue as #4217.
=> Use `innerWidth`/`innerHeight` instead of `outerWidth`/`outerWidth`

docs/For Users/Advanced/JavaScript Contexts in NW.js.md, docs/For Users/Advanced/Transparent Window.md
Corrected two simple typo errors I discovered in docs
=> Typo errors in docs

src/resources/api_nw_menuitem.js, test/manual/issue4313-menu-after-nav/index.html, test/manual/issue4313-menu-after-nav/next.html, test/manual/issue4313-menu-after-nav/package.json
Move menus implementation to background page.
This is a partial fix for #4313, which works for navigating to
internal pages.
=> Make menu callback work after navigation

src/api/nw_screen_api.cc
NWJS app allows running on origins other than `chrome-extension://*/*`.
The origin should then be from the senders URL, in order not to fail
the origin checking in `DesktopStreamsRegistry::RequestMediaForStreamId`.
See also nwjs/chromium.src#11
=> Fixed similar issue of #4579 for `nw.Screen.DesktopCaptureMonitor`

src/nw_package.cc
nw::Package was initialized before logging module. Log in constructor
will cause creating another log file.
Fixed #4637
=> Remove log in nw::Package constructor

docs/For Users/Package and Distribute.md
Clarify files can be safely removed (fixed #4676)
=> Updated docs on package and distribution

tools/package_binaries.py
libexif is loaded on Windows at start up. When loading failed, it
will generate debug.log in the same directory of nw.exe without
`--enable-logging`. Ship `libexif.dll` with NW.js will fix this issue.
On Mac OS X, it's already shipped with NW.js. On Linux, it loads
`libexif.so.12` in system path.
Fixed #4637
=> [win] ship with libexif.dll

docs/For Users/Advanced/Customize Menubar.md, docs/References/Window.md, src/api/nw_window_api.cc, src/nw_content_mac.mm
Previously in 0.12.x the visibility of menubar on fullscreen/kiosk
mode is inconsistent on different platforms. Since 0.13.0, the
menubar is always visible on fullscreen / kiok mode. Using
`win.menu=null` can remove the menubar manually. This gives
developers better control on the menubars.
This patch implemented `win.menu=null` to completely remove the
menubar on Linux and Windows, and cleared out the menubar on Mac.
The patch also updated the docs about menubar visibility on
fullscreen mode.
Fixed #4725
=> implemented `win.menu=null` to remove menubar

docs/References/Clipboard.md, src/api/nw_clipboard.idl, src/api/nw_clipboard_api.cc, src/api/nw_clipboard_api.h, src/resources/api_nw_clipboard.js
Following types are supported:
* Text
* HTML
* RTF (Rich Text Format)
* image of PNG and JPEG
Fixed #2677
=> Extended `nw.Clipboard` to support multiple data types

src/api/base/base.cc
=> Initialize members of `nw::Base` explicitly

src/resources/api_nw_menuitem.js
`click` property is documented as optional. It should not be an
error if `click` doesn't exist.
fixed #4862
=> not display errors if menuitem don't have `click` property

docs/For Users/Debugging with DevTools.md
Just correct Node.jd to Node.js
=> Correct Node.jd mistake

src/api/menu/menu_mac.mm
Disabled contextual menu plug-in items on mac.
=> Disabled contextual menu plug-in items on mac.

src/browser/menubar_view.cc
Foreground colors used by menubar buttons should be consistent
with themes provided by the system. We use same foreground color
as menu items.
fixed #5007
=> [linux] fixed foreground colors for menubar

docs/References/Clipboard.md, src/api/nw_clipboard.idl, src/api/nw_clipboard_api.cc, src/api/nw_clipboard_api.h, src/resources/api_nw_clipboard.js
following new APIs added:
* `clip.set(clipboardDataList)`
* `clip.set(clipboardData)`
* `clip.get(clipboardDataList)`
* `clip.get(clipboardData)`
fixed #4929
=> added new APIs for read/write multiple types of data to clipboard

src/resources/api_nw_window.js
This fixes a regression since nw13 where the return value of Window.eval() and Window.evalNWBin() would be lost.
BTW, it would be great if this could also be merged into the nw14 branch.
=> Make Window.eval() and Window.evalNWBin() return result

docs/For Users/Advanced/Use Native Node Modules.md
Due to V8 differences (#5025), native modules built from npm or
node-gyp can't be used by NW.js 0.15.x directly. Remove the docs
about the usage of npm & node-gyp.
This reverts commit 9f2a798bdab5c50cbd0cb480141d8fdefa989f48.
=> Revert "[docs] native module with npm"

src/api/menu/menu_delegate.cc, src/api/menuitem/menuitem_views.cc
fixed #5026 
@rogerwang This is a patch for issues on NW14 for Win XP. If you think necessary for NW16, please merge this patch.
=> do not return invalid shortcuts for menu items

src/resources/api_nw_window.js
Two bugs brings from commit bc016d4:
* missing `height` argument to `resize` event (fixed #4993)
* should use `self` instead of `this` in `navigation` event callbacks
=> fixed arguments passed to `nw.Window` API callbacks

tools/win_delay_load_hook.cc
Made the modifications I talked about in issue #5088 .
Changed `PfnDliHook __pfnDliNotifyHook2 = load_exe_hook;` to `decltype(__pfnDliNotifyHook2) __pfnDliNotifyHook2 = load_exe_hook;` so it'll work with the new VS build tools on Windows.
Also added the header guard.
e: Quick edit, here's the PR from node-gyp discussing the change:
https://github.com/nodejs/node-gyp/pull/952
=> Updated win_delay_load_hook.c to work with node-gyp@3.4.0

docs/For Users/Package and Distribute.md
Removed detailed steps for using `nw-builder` and listed `nwjs-builder`
and `nw-builder` side-by-side.
=> [doc] updated Quick Start section for "Package and Distribute"

nw.gypi, src/api/base/base_mac.h, src/api/base/base_mac.mm, src/api/menu/menu.h, src/api/menu/menu_mac.mm, src/api/menuitem/menuitem.h, src/api/menuitem/menuitem_mac.mm, src/api/nw_current_window_internal.idl, src/api/nw_object.idl, src/api/nw_object_api.cc, src/api/nw_object_api.h, src/api/nw_window_api.cc, src/api/nw_window_api.h, src/api/object_manager.cc, src/nw_content_mac.h, src/nw_content_mac.mm, src/resources/api_nw_menu.js, src/resources/api_nw_menuitem.js, src/resources/api_nw_object.js, src/resources/api_nw_window.js
On Mac, the system will add several menu items to Edit menu, like
`Emoji & Symbols` or `Start Dictation...`. These items are added
after setting main menu. This patch will update menu items after
setting main menu. Then developers can iterate items under edit
menu and remove corresponding items.
fixed #2812
=> [osx] update menuitems after setting main menu

src/browser/menubar_view.cc
fixed #5150 
This feature existed in pre-13 releases. It should be supported.
=> activate menuitem of menubar button when clicked

src/resources/api_nw_tray.js, test/sanity/issue5202-tray-menu-id/index.html, test/sanity/issue5202-tray-menu-id/package.json, test/sanity/issue5202-tray-menu-id/test.py
Previous change in 4b9e319 used id allocated from `nw.Obj` instead
of from `context_menus` for `nw.Menu` and `nw.MenuItem`. But `nw.Tray`
was still using the old way, which generated conflicted id.
fixed #5202
=> fix id allocation for tray

BUILD.gn, src/api/base/base_mac.mm, test/sanity/issue5229-menubar-crash/index.html, test/sanity/issue5229-menubar-crash/package.json, test/sanity/issue5229-menubar-crash/test.py
These two files provided util APIs for storing & retrieving NW menu
objects within `NSMenu`. Added them for GN build to prevent crashes
when creating menubar on Mac.
* test case: test/sanity/issue5229-menubar-crash
* fixed #5229
=> [mac] added base_mac.mm & base_mac.h to mac build

test/sanity/issue3780-jailed-elements/test.py, test/sanity/issue3780-jailed/test.py, test/sanity/issue3835-inspect-crash/test.py, test/sanity/issue4121-inpect-node-crash/test.py, test/sanity/issue4269-click-link-crash/test.py
Following test cases are affected by devtools update during nw18
update:
* issue3780-jailed-elements
* issue3780-jailed
* issue3835-inspect-crash
* issue4121-inpect-node-crash
* issue4269-click-link-crash
fixed #5273 #5274 #5275 #5276
=> updated test cases for nw18 update

docs/For Users/Advanced/JavaScript Contexts in NW.js.md
Fix typo: `achive` -> `achieve`
=> Fix typo: `achive` -> `achieve`

docs/For Users/Migration/From 0.12 to 0.13.md
* `nw.Window.get(winObj)` is now supported. So it's removed from
list.
* min/max width/height options are working on Linux. Only resizable
is not working now due to upstream issues.
* added `isDevToolsOpen` as not supported
=> [doc] updated known issues

test/sanity/issue3780-jailed/test.py, test/sanity/issue3835-inspect-crash/test.py, test/sanity/nw_util.py
`driver.find_element_by_id().send_keys()` will cause an error of
"cannot focus element". This happens for typing into inputs of console
of DevTools, which is using CodeMirror. Use `ActionChains(driver).send_keys()`
can workaround this issue.
Fixed test cases:
* issue3780-jailed
* issue3835-inspect-crash
=> [test] use ActionChains send keys to element avoid webdriver issues

test/sanity/worker-process-stdout/index.html, test/sanity/worker-process-stdout/package.json, test/sanity/worker-process-stdout/test.py, test/sanity/worker-process-stdout/worker.js, test/sanity/worker-require-module/index.html, test/sanity/worker-require-module/node_modules/test/index.js, test/sanity/worker-require-module/node_modules/test/package.json, test/sanity/worker-require-module/package.json, test/sanity/worker-require-module/test.py, test/sanity/worker-require-module/worker.js, test/sanity/worker-sharedworker/index.html, test/sanity/worker-sharedworker/package.json, test/sanity/worker-sharedworker/sharedworker.js, test/sanity/worker-sharedworker/test.py, test/sanity/worker-stream-event/index.html, test/sanity/worker-stream-event/package.json, test/sanity/worker-stream-event/test.py, test/sanity/worker-stream-wrap/index.html, test/sanity/worker-stream-wrap/package.json, test/sanity/worker-stream-wrap/test.py, test/sanity/worker-stream-wrap/worker.js
* process.stdout error when worker is exited
* require external modules failed in worker
* node in sharedworker
* stream events not fired in DOM when worker enabled
* stream_wrap failed in worker
=> [test] add 4 test cases for worker

docs/For Users/Advanced/Use Native Node Modules.md
Simplified the instructions of building native modules by dividing
into LTS and non-LTS releases.
Updated link and filename to `win_delay_load_hook.cc` and fixed #5396
=> [doc] refactored doc for building native modules

src/nw_package.cc
When starting apps from a folder of parent, such as `nw ../app_root/`,
icon file cannot be loaded correctly. The root cause is that
`base::ReadFileToString` refused for path referencing to parent
folder. However path of icon obtained by `nw::Package::ConvertToAbsolutePath`
is still a relative path.
The patch fixes `ConvertToAbsolutePath` to return a absolute path.
fixed #5402
=> Fixed `ConvertToAbsolutePath` to return a absolute path

docs/For Users/Advanced/Use Native Node Modules.md
Use `npm_config_` environments to override default behaviors of
npm and node-gyp. `npm_config_node_gyp` can be used to replace
`node-gyp` with `nw-gyp` during `npm install`.
=> [doc] updated docs for rebuilding native modules

src/api/menuitem/menuitem.cc, src/api/menuitem/menuitem_mac.mm, src/api/menuitem/menuitem_views.cc
* modifiers should be case insensitive
* command and super should be supported same as cmd on macOS
fixed #5451
=> fixed bugs of modifiers of nw.MenuItem

docs/References/Menu.md, src/api/menu/menu.h, src/api/menu/menu_views.cc, src/api/nw_window_api.cc, src/browser/global_menu_bar_registrar_x11.cc, src/browser/global_menu_bar_registrar_x11.h, src/browser/global_menu_bar_x11.cc, src/browser/global_menu_bar_x11.h
Global menubar is implemented via dbus API. And it will fallback
to local menubar when no global menubar available.
fixed #2718
=> [linux] enabled global menubar on Ubuntu

test/sanity/cookie-lost-devtools-close/test.py
Fixed the case of cookie-lost-devtools-close
=> [test] switch to devtools window w/o specifying window handle

src/api/menu/menu.h, src/api/menu/menu_views.cc, src/api/menuitem/menuitem.h, src/api/menuitem/menuitem_views.cc, src/api/nw_window_api.cc
This commit fixed following issues:
* shortcuts was not unregistered when the item was removed or detached
* shortcuts didn't work with inserted items
fixed #5657
=> fixed multiple menu shortcuts issues

src/api/menu/menu.h, src/api/menu/menu_views.cc, src/api/menuitem/menuitem.h, src/api/menuitem/menuitem_views.cc, src/api/nw_window_api.cc
This commit fixed following issues:
* shortcuts was not unregistered when the item was removed or detached
* shortcuts didn't work with inserted items
fixed #5657
=> reland "fixed multiple menu shortcuts issues"

docs/For Users/Debugging with DevTools.md
`--` will become `–` after mkdocs and mislead users , so adding ` `` ` to avoid this.
=> [doc] avoiding two en dash become an em dash after mkdocs

docs/For Users/Advanced/Autoupdates.md
The documentation (http://docs.nwjs.io/en/latest/For%20Users/Advanced/Autoupdates/#autoupdates) recommends node-webkit-updater and nwjs-autoupdater.
As an alternative one can consider https://github.com/dsheiko/nw-autoupdater
It provides an API (like node-webkit-updater, but cleaner with use of async/await) to customize auto-update flow in one's app including download/install progress
Tested with NW.JS 0.21.3 on Ubuntu 16.04, macOS Sierra and Window 10
=> adding PR - for nw-autoupdater

docs/For Users/Package and Distribute.md
Greetings.
I am the author of `nwjs-builder` and `nwjs-builder` was made in that particular period when `nw-builder` didn't support NW.js 0.13 and later.
Although there were some issues but `nwjs-builder` has already been working for months without being maintained.
Recently I found it difficult to fix issues in `nwjs-builder` and was shocked to discover the ecology difference between NW.js and Electron. I decided to rewrite a new builder tool for NW.js, inspired by `electron-builder`, as a total replacement to `nwjs-builder`, which I would drop support at any time.
Here comes `nwjs-builder-phoenix`. I am sorry to bring up a new package name but look, we have:
* a shining tool rewritten with TypeScript, with
* simplified commands and configurations
* concurrent building
* powerful NSIS …
=> [docs] replace nwjs-builder with nwjs-builder-phoenix

docs/For Users/Advanced/Transparent Window.md, src/browser/native_window.cc
use disable-gpu-compositing instead of disable-gpu
this pull request dependent on https://github.com/nwjs/chromium.src/pull/89
please also patch nw24
=> [Transparency][Win][OSX] use disable-gpu-compositing instead of disable-gpu

tools/package_binaries.py
Since chromium 61, the swiftshader OpenGL libraries need to be included in the linux packages.
This adds two files to the package:
swiftshader/libEGL.so
swiftshader/libGLESv2.so
=> build-dist: include swiftshader OpenGL API libs

docs/For Users/FAQ.md
Hi, I had a look at the FAQ and it mentioned `AnugarJS` which I've taken to be a typo of `AngularJS`.
=> Correct typo in FAQ.md

test/sanity/issue5882-debugging-tools-crash/index.html, test/sanity/issue5882-debugging-tools-crash/package.json, test/sanity/issue5882-debugging-tools-crash/test.py
- Add test for issue #5882
- This case is failed on failed version 0.21.2, pass on fixed version 0.27.4
=> [test] Add test case for issue #5882

test/sanity/issue6229-webview-executeScript/index.html, test/sanity/issue6229-webview-executeScript/package.json, test/sanity/issue6229-webview-executeScript/site.html, test/sanity/issue6229-webview-executeScript/test.py
- Add test for issue #6229
- This case is failed on failed version 0.26.0, pass on fixed version 0.27.4
=> [test] fix test 6229

docs/For Users/Debugging with DevTools.md
Add in instructions for using Vue-DevTools in NW.js, based on:
* https://github.com/TheJaredWilcurt/nw-vue-devtools
=> Add Vue example to "Using devtools extensions"

docs/For Users/Package and Distribute.md
If we're going to update the Helper app binary, why not the main app binary?
This relates to https://github.com/nwjs/nw.js/issues/4293
=> Update Mac package docs to rename nwjs binary

docs/For Users/FAQ.md
* Added instructions for VSCode intellisense
* This comes from https://github.com/nwjs/nw.js/issues/7076 and https://github.com/nwjs/nw.js/issues/6577#issuecomment-497665252
* Minor formatting and grammar
* Also added in a link to my "Setting up NW.js + Angular" tutorial. and the repo for the tutorial
* https://dev.to/thejaredwilcurt/angular-cli-and-nwjs-for-development-49gl
* https://github.com/nwutils/nw-angular-cli-example
* I believe this is the first image used in the docs. If it should be uploaded to the repo or removed, let me know.
=> Add VSCode Intellisense setup to FAQ

docs/For Users/Getting Started.md
Excuse me for the brupt PR, but it says "Issue tracker is only for bugs and feature requests" so I didn't create issue beforehand.
The original `style="width: 100%; height: 100%;"` may mislead new user to expect the right click works everywhere in the window, while it doesn't really.
=> Improve code of example 2 in tutorial

tools/package_binaries.py
Fixes #7378 by removing `natives_blob.bin` from packaging requirements.
Also adds support for ARM builds where the NaCl IRT is named differently.
=> Update binary packaging to support ARM builds

test/sanity/issue7503-close/local.html, test/sanity/issue7503-close/main.html, test/sanity/issue7503-close/main.js, test/sanity/issue7503-close/package.json, test/sanity/issue7503-close/test.py
Test for #7503 (close event not firing on window with remote url).
I wasn't exactly sure how to properly test this type of NW.js event via Selenium, so hopefully this is not too complicated.
It opens 3 windows. One main window, one window with local file and one with remote url. It creates button in both window with local file and remote url and then it clicks on those buttons via Selenium. That should close both windows and change the content in `result_local `and `result_remote` elements in the main window via the close event.
=> [test] add test for nwjs/nw.js#7503

docs/For Users/Package and Distribute.md
The title says it all. A few minor typo I noticed in the docs.
=> Packaging docs: Correct typo with Linux app file zip name

LICENSE
Several words in that license text were broken in two in
the middle and was leading to possible issues in license
identification.
This has been detected by scancode-toolkit as highly similar
to but not exactly as the commonly used MIT license text.
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>
=> Fix broken words in LICENSE

docs/For Users/Advanced/JavaScript Contexts in NW.js.md
Looks like Node was enabled in Workers a few years ago, so this should be updated
=> Update Web Worker documentation

BUILD.gn, src/nw_content_mac.mm
These changes allow developers to use the Assessment Mode capabilities of the Mac Operating System.
Now when Kiosk Mode is enabled, the executable is signed with the correct entitlements and certificate and the user is on MacOS 10.15.4 or higher, Assessment Mode will be activated, meaning the user can no longer leave the app, their clipboard gets cleared and more: https://developer.apple.com/documentation/automaticassessmentconfiguration.
If they do not fulfil these conditions, nothing happens.
I personally have little experience with Objective-C, so any suggestions for improvements are welcome. Merging this into NW.JS would really help us out, otherwise we'll have to maintain a separate version of this framework.
Thank you in advance!
=> MacOS Assessment Mode enabled via Kiosk Mode

src/api/menuitem/menuitem_mac.mm
This patch attempts to fix https://github.com/nwjs/nw.js/issues/7739
Adding extra cases which could handle function key mask since macOS 12 could use Function key as modifiers. Adding a string length guard as well to avoid further changes which may lead to crash.
Since `NS*KeyMask` are deprecated from 10.12, migrating to `NSEventModifierFlag*` as well.
=> fix: handle function key mask since macos 12

docs/For Users/Package and Distribute.md
The helper app was moved to a framework, and the launcher name is `CFBundleExecutable`, not `CFBundleDisplayName`.
=> Update Mac packaging instructions

tools/payload.cc
Fixes #7933.
Other methods in this file were already migrated to move semantics, but one may have been overlooked.
=> bugfix: Build error in `payload` dist tool.

docs/For Users/Package and Distribute.md
As stated in https://github.com/nwjs/nw.js/issues/7693, nwjs-builder-phoenix has not be maintained for years.
Every now and then, there are more CVE opened on dependencies, that cannot be updated with this package, this shouldn't be a recommended package builder anymore.
This PR removes link to this builder in the documentation.
=> fix(docs): Remove unmaintained way to package nw.js from docs

src/browser/nw_extensions_browser_hooks.cc
Previous fix was not sufficient.  We also need to use the updated Chromium `base::Value` api call, `SetByDottedPath()` when manipulating the manifest values via a dotted path name.
=> Fixes nwjs#8039; Grey default icon in taskbar on Windows

patch/patches/icu.patch
Description
Depends on https://github.com/nwjs/node/pull/58.
This is a follow up of https://github.com/nwjs/nw.js/pull/8134 which turned out to be an incorrect fix. This PR will allow nw-builder to build node native addons (directly via node-gyp using NW.js node headers) using Python 3. Since only ICU requires `v8_host_byteorder`, I have moved it there. After making these changes, I am able to successfully build Node. I'm planning to submit a test case for this in a subsequent PR.
=> Enable building Node native addon via Python 3

docs/For Users/Migration/From 0.12 to 0.13.md, docs/References/Window.md, src/resources/api_nw_newwin.js
fix: https://github.com/nwjs/nw.js/issues/4487
=> add isDevToolsOpen
