nwjs/nw.js

- src/nw_notification_manager.cc
- src/nw_notification_manager.h
- src/nw_notification_manager_linux.cc
- src/nw_notification_manager_linux.h
- src/nw_notification_manager_mac.h
- src/nw_notification_manager_mac.mm
- src/nw_notification_manager_toast_win.cc
- src/nw_notification_manager_toast_win.h
- src/nw_notification_manager_win.cc
- src/nw_notification_manager_win.h
- src/shell_content_browser_client.cc
- src/shell_content_browser_client.h
@rogerwang I've cleanup / fix the desktop notification feature
> nw12 notification

- src/nw_shell.cc
- src/shell_devtools_frontend.cc
- src/shell_devtools_frontend.h
Fixed rogerwang/node-webkit#2660
Fixed rogerwang/node-webkit#2603
> Fix devtools

- src/browser/native_window.cc
- src/browser/native_window_aura.cc
- src/browser/native_window_mac.mm
@rogerwang I've fixed and tested all the transparency features for NW12
this pull request will need https://github.com/rogerwang/chromium.src/pull/31
> nw12 transparency rebase

- CHANGELOG.md
- tools/make-nw-headers.py
1. correct `uv.h` include path error
2. make it works same as `make-nw-header.sh`
> update make-nw-header tool

- src/nw_shell.cc
- src/nw_shell.h
add Window.on("progress", function (progress) {
//progress 0.0 -> 1.0
});
> add Window progress event

- AUTHORS
> AUTHORS file (about PR #3251)

- README.md
I make all the *really* useful pull requests.
> Updated link to nwjs.io in README.md

- AUTHORS
Update AUTHORS file for PR #3340
> Update AUTHORS file for PR #3340

- tools/make-nw-headers.py
- tools/package_binaries.py
fix 'header files version on postfix'
> add pre-release support

- AUTHORS
> Add name to authors

- nw.gypi
- src/api/nw_current_window_internal.idl
- src/api/nw_menu.idl
- src/api/nw_menu_api.cc
- src/api/nw_menu_api.h
- src/api/nw_menu_api_mac.mm
- src/api/nw_window_api.cc
- src/api/nw_window_api.h
- src/api/nw_window_api_mac.mm
- src/resources/api_nw_menu.js
@rogerwang this is my pull request for implementation of following api(s):
```javascript
Menu.createMacBuiltin
Window.setBadgeLabel
Window.requestAttention
Window.setProgressBar
```
> Nw13 pullrequest

- nw.gypi
- src/api/_api_features.json
- src/api/nw_tray_api.h
- src/api/object_manager.cc
- src/api/tray/tray_aura.cc
- src/api/tray/tray_mac.mm
- src/nw_custom_bindings.cc
- src/resources/api_nw_menu.js
- src/resources/api_nw_tray.js
@rogerwang this is my pull request for Tray API
it also needs code changes in chromium:
https://github.com/nwjs/chromium.src/pull/43
> [Tray API] fixes for nw13

- src/api/nw_app.idl
- src/api/nw_app_api.cc
- src/api/nw_app_api.h
- src/resources/api_nw_app.js
@rogerwang I've just migrated App.dataPath API
> Migrate app datapath

- src/nw_content.cc
pre13 shim has to be injected before other user injected scripts. And also this patch fixed the bug that shim doesn't run without having `inject-js-start` in manifest.
> Fixed shim script injecting

- src/api/_api_features.json
- src/api/menu/menu.h
- src/api/menu/menu_delegate.cc
- src/api/menu/menu_views.cc
- src/api/menuitem/menuitem.cc
- src/api/menuitem/menuitem.h
- src/api/menuitem/menuitem_mac.mm
- src/api/menuitem/menuitem_views.cc
- src/api/nw_menu.idl
- src/api/nw_menu_api.cc
- src/api/nw_menu_api.h
- src/api/nw_window_api.cc
- src/nw_content.cc
- src/resources/api_nw_menu.js
- src/resources/api_nw_menuitem.js
> Fix for nw.Menu & nw.MenuItem API

- src/api/menuitem/menuitem.cc
- src/api/menuitem/menuitem.h
- src/api/menuitem/menuitem_mac.mm
- src/api/menuitem/menuitem_views.cc
This patch fixed keys on Mac and also compatible with old key values.
> [Mac] Added support for new key names on menubar

- AUTHORS
- src/api/nw_window.idl
- src/api/tray/tray_aura.cc
- src/resources/api_nw_window.js
@rogerwang this is my pull request for transparency support on nw13
it also needs https://github.com/nwjs/chromium.src/pull/55
> Transparency for nw13

- src/resources/api_nw_window.js
Should I still do pull requests or should I push directly to nw.js?
> fix requestAttention api

- mkdocs.yml
@rogerwang This fixed the mkdocs build failure
> Fixed for mkdocs

- test/remoting/require-path/common.js
- test/remoting/require-path/index.html
- test/remoting/require-path/package.json
- test/remoting/require-path/public/index.html
- test/remoting/require-path/public/test.js
- test/remoting/require-path/test.js
- test/remoting/require-path/test.py
The relative path resolution in browser context should always relative to the **main HTML** file.
> Added test case for testing require(path)

- src/resources/nw_pre13_shim.js
- test/remoting/require-methods/index.html
- test/remoting/require-methods/package.json
- test/remoting/require-methods/test.py
> Copy methods of Node `require` to shim

- docs/References/Manifest Format.md
`single-instance` is deprecated.
> Updated docs for `single-instance`

- test/remoting/manifest-html-main-inside/inside/index.html
- test/remoting/manifest-html-main-inside/package.json
- test/remoting/manifest-html-main-inside/test.py
- test/remoting/manifest-html-main/index.html
- test/remoting/manifest-html-main/package.json
- test/remoting/manifest-html-main/test.py
- test/remoting/manifest-js-main-inside/index.html
- test/remoting/manifest-js-main-inside/inside/index.js
- test/remoting/manifest-js-main-inside/package.json
- test/remoting/manifest-js-main-inside/test.py
- test/remoting/manifest-js-main/index.html
- test/remoting/manifest-js-main/index.js
- test/remoting/manifest-js-main/package.json
- test/remoting/manifest-js-main/test.py
Added a bunch of tests for `main` in manifest.
> Mainifest main

- test/remoting/issue4180-remote-win-open/http-server.py
- test/remoting/issue4180-remote-win-open/index.tpl
- test/remoting/issue4180-remote-win-open/package.json
- test/remoting/issue4180-remote-win-open/test.py
Actually I can't reproduce the same issue with older beta3 build or even beta2 build. However the test case should be working as a positive case.
> test case for issue #4180

- test/remoting/issue4118-mac-quit/index.html
- test/remoting/issue4118-mac-quit/package.json
- test/remoting/issue4118-mac-quit/test.py
> test case for issue #4118

- docs/For Users/FAQ.md
> Added FAQ for leaving fullscreen mode

- test/remoting/issue3780-jailed-elements/child.html
- test/remoting/issue3780-jailed-elements/index.html
- test/remoting/issue3780-jailed-elements/package.json
- test/remoting/issue3780-jailed-elements/test.py
- test/remoting/issue3780-jailed/package.json
* added new case for checking "Elements" panel
* fixed package name
> test case for issue #3780

- docs/References/App.md
- src/resources/api_nw_app.js
- test/remoting/app-argv/index.html
- test/remoting/app-argv/package.json
- test/remoting/app-argv/test.py
* Implemented `App.fullArgv` API
* Updated docs for `App.argv`, `App.fullArgv` and `App.filteredArgv`
* Added test case
Fixed #4231
> implemented `App.fullArgv` and fixed `App.argv`

- test/remoting/capture_page/test.py
- test/remoting/issue3780-jailed-elements/test.py
- test/remoting/issue3780-jailed/test.py
- test/remoting/issue3835-inspect-crash/test.py
- test/remoting/issue4007-reload-lost-app-window/test.py
- test/remoting/issue4118-mac-quit/test.py
- test/remoting/issue4121-inpect-node-crash/test.py
- test/remoting/issue4130-win-open-close-fail-http/test.py
- test/remoting/issue4138-win-not-close/test.py
- test/remoting/issue4164-close-not-quit/test.py
- test/remoting/issue4184-no-opener/test.py
- test/remoting/issue4187-close-hidden/test.py
- test/remoting/issue4269-click-link-crash/test.py
- test/remoting/new-win-policy/test.py
- test/remoting/nw_util.py
- test/remoting/open-remote/test.py
This patch waited for expected number of opening windows before
switching to new popup or devtools window.
This patch also extracted common functions to `nw_util.py`.
> Safer window switching for test cases

- docs/For Users/FAQ.md
> Updated FAQ for AnuglarJS 2

- docs/References/Shortcut.md
Per request by https://groups.google.com/forum/#!topic/nwjs-general/zjGJy5rZEf4
> Update for case insensitive in shortcut key code

- src/resources/api_nw_app.js
- src/resources/api_nw_shortcut.js
- test/remoting/shortcut-event/index.html
- test/remoting/shortcut-failure/index.html
- test/remoting/shortcut-normal/index.html
> Rename `App.(un)registerGlobalHotkey` to `App.(un)registerGlobalHotKey`

- docs/For Users/Advanced/JavaScript Contexts in NW.js.md
> Correct some typos in "docs/For Users/Advanced/JavaScript Contexts in NW.js.md"

- src/nw_shell.cc
- src/shell_devtools_frontend.cc
fixed rogerwang/node-webkit#2660
fixed rogerwang/node-webkit#2603
> Fixed devtools issue for nw12

- src/api/nw_object.idl
- src/browser/menubar_controller.cc
- src/resources/api_nw_menuitem.js
- src/resources/api_nw_object.js
> Show menubar menus from top-left anchor

- docs/References/Manifest Format.md
- src/nw_content.cc
- src/nw_content.h
- src/resources/api_nw_window.js
- test/remoting/issue4221-win-open-manifest/index.html
- test/remoting/issue4221-win-open-manifest/package.json
- test/remoting/issue4221-win-open-manifest/test.py
> Use window subfields in manifest for newly created windows

- docs/For Users/Advanced/Customize Menubar.md
- docs/For Users/Migration/From 0.12 to 0.13.md
- docs/References/Menu.md
- docs/index.md
> Added docs of `Customize Menubar`

- docs/For Users/Migration/From 0.12 to 0.13.md
- docs/References/Manifest Format.md
- docs/References/Window.md
- test/remoting/issue4493-win-open-size/index.html
- test/remoting/issue4493-win-open-size/package.json
- test/remoting/issue4493-win-open-size/test.py
This patch contains doc changes and test case. The real fix in on
Chromium side.
Partial fix for #4493
> Fix window open size

- docs/For Users/Advanced/Use Native Node Modules.md
> Update Use Native Node Modules.md

- test/remoting/issue4521-notification-perm/index.tpl
- test/remoting/issue4521-notification-perm/test.py
Using `chrome.contentSettings` to alter notification permissions.
> Updated test case for #4521

- docs/For Developers/Writing Documents for NW.js.md
- mkdocs.yml
> Reordered the docs

- test/remoting/issue4579-capture-remote/http-server.py
- test/remoting/issue4579-capture-remote/index.html
- test/remoting/issue4579-capture-remote/test.py
The test case is based on `nw.Screen.DesktopCaptureMonitor`.
> Added test case for issue #4579

- src/api/menuitem/menuitem_views.cc
- test/remoting/issue2261-disable-menu-hotkey/index.html
- test/remoting/issue2261-disable-menu-hotkey/package.json
- test/remoting/issue2261-disable-menu-hotkey/test.py
> Disable hotkey when menuitem is disabled

- src/nw_package.cc
The path finding logic of NW.js app:
1. Extract self
2. `<exe-folder>`
3. `<exe-folder>/package.nw`
4. CLI arguments:
* `--nwapp`
* first argument
5. default
Fixed #4681
> Reordered path finding for backward compatible with nw12

- docs/For Developers/Enable Proprietary Codecs.md
> Updated docs for building proprietary codecs easier

- src/api/shell/shell.cc
> Use correct OpenItemType

- src/browser/menubar_controller.cc
> use master controller for active menu model

- patch/patch.cfg
- patch/patches/angle.patch
Patched angle to call `IDXGIFactory::MakeWindowAssociation` after
creating swap chain to disable ALT-ENTER hotkey.
fixed #4741
> Patched angle to disable ALT-ENTER hotkey

- patch/patch.cfg
- patch/patches/webrtc_window_capturer.patch
Fixed screen-desktopcapturemonitor test case after M50
> [mac] sort windows in front to back order

- src/api/menu/menu.cc
> recalculate coordinations of menu.popup() for zoom

- docs/References/Tray.md
> updated docs on the usage of tray when page can be navigated

- src/resources/api_nw_window.js
> make `this` in event listener reference to `nw.Window`

- custom_theme/searchbox.html
- mkdocs.yml
see https://github.com/rtfd/readthedocs.org/issues/1088#issuecomment-221418742
> workaround searching for RTD

- patch/patches/angle.patch
> updated angle patch for nw16

- docs/For Developers/Building NW.js.md
- docs/For Developers/Repositories.md
* Added manual checkout steps for customized repos
* Removed unused repos from the list
> Update build instructions

- src/resources/api_nw_tray.js
> send positions arguments to click event handler of Tray

- src/api/nw_screen_api.cc
> request audios when registering sources

- src/api/menu/menu_delegate.cc
- src/api/menuitem/menuitem_views.cc
> do not return invalid shortcuts for menu items

- docs/For Users/Migration/From 0.12 to 0.13.md
- docs/For Users/Package and Distribute.md
> [doc] fixed typos for docs

- patch/patches/webrtc_window_capturer.patch
> updated patch for webrtc_window_capturer

- README.md
Nothing important, but it's better said like this.
> Fix English in Readme

- docs/References/Screen.md
> [doc] fix a typo in doc

- src/browser/menubar_view.cc
> activate menuitem of menubar button when clicked

- docs/For Developers/Enable Proprietary Codecs.md
> [doc] Updated docs for building proprietary codecs

- docs/For Users/Getting Started.md
> [doc] updated getting started for using js as main

- src/api/nw_window.idl
> fixed `show_in_taskbar` option for `nw.Window.open`

- tools/win_delay_load_hook.cc
> fixed nw-gyp build failure with UNICODE set

- src/resources/api_nw_window.js
> fixed `nw.Window.isTransparent`

- src/api/menu/menu.cc
> fix popup menu in background page crashes nw

- docs/References/Window.md
fixed inject_js_start and inject_js_end link
> [doc] fixed inject js link in window.md

- test/sanity/cookie-lost-devtools-close/bg.js
- test/sanity/cookie-lost-devtools-close/index.html
- test/sanity/cookie-lost-devtools-close/test.py
- test/sanity/nw_util.py
Reland previous patch in e60392435d503805889d0e79eba8162fb78cbd79
> [test] added a test case for cookie lost after devtools closed

- docs/References/Window.md
Hi @rogerwang!
Here is the documentation update, as you suggested here: https://github.com/nwjs/chromium.src/pull/59#issuecomment-272859091
Cheers!
> [IMP] Added documentation for the copies option in the printing API

- docs/References/App.md
- src/api/nw_app.idl
- src/api/nw_app_api.cc
- test/sanity/app-getproxyforurl/bg.js
- test/sanity/app-getproxyforurl/index.html
- test/sanity/app-getproxyforurl/package.json
- test/sanity/app-getproxyforurl/test.py
And implement this feature in nw_app_api.cc.
(cherry picked from commit c45f6864d3693056d2d13871441a9f49e73ec830)
> Fix #916: support pac_url and auto proxy detection

- docs/For Developers/Contributors of Documents.md
- docs/For Users/Advanced/Autoupdates.md
- mkdocs.yml
Adds listing of community solutions to add autoupdate feature to NWJS apps
> [doc] Added "Autoupdates.md"

- docs/References/Window.md
- src/resources/api_nw_window.js
> Adds the logic when removeAllListeners has no parameter

- docs/References/Chrome Extension APIs.md
- docs/References/webview Tag.md
Documentation for this pull request:
https://github.com/nwjs/chromium.src/pull/71
Our project:
https://groups.google.com/forum/#!topic/nwjs-general/TmZUq-JHIuQ
> Cookies API on webview documentation.

- docs/References/Window.md
- src/resources/api_nw_window.js
iframe's window should not have independent Window object
fixed #5043, #5044, #5755
> Correct the function of Window.get inconformity with the original design

- README.md
> Added space before header demo to make it a header

- test/sanity/issue4221-win-open-manifest/index.html
- test/sanity/issue4221-win-open-manifest/test.py
Also correct some mismatch between design and implementation
> [test] update the case to cover the scenario of bug #5517

- src/renderer/nw_extensions_renderer_hooks.cc
Also remove redundant whitespaces in the adjacent empty line.
> Fix a suspicious typo.

- .github/ISSUE_TEMPLATE.md
https://github.com/nwjs/nw.js/issues/6089
> Updateing template

- test/sanity/issue6143-mac-setProgressBar-crash/index.html
- test/sanity/issue6143-mac-setProgressBar-crash/package.json
- test/sanity/issue6143-mac-setProgressBar-crash/test.py
- Add test for issue #6143 
- This case is failed on failed version 0.25.0, pass on fixed version 0.27.4
> [test] add test for issue#6143

- test/sanity/issue6001-devtools-open-crash/index.html
- test/sanity/issue6001-devtools-open-crash/index.js
- test/sanity/issue6001-devtools-open-crash/package.json
- test/sanity/issue6001-devtools-open-crash/test.py
- Add test for issue #6001
- This case is failed on failed version 0.23.5, pass on fixed version 0.27.4
> [test] Add test for issue6001

- test/sanity/issue5906-webview-getCookieStoreId/index.html
- test/sanity/issue5906-webview-getCookieStoreId/package.json
- test/sanity/issue5906-webview-getCookieStoreId/test.py
- Add test for issue #5906
- This case is pass on v0.22.2 and v0.27.4
> [test] add test for issue5906

- test/sanity/issue6113-mac-create-crash/index.html
- test/sanity/issue6113-mac-create-crash/package.json
- test/sanity/issue6113-mac-create-crash/test.py
- Add test for issue #6113
- This test is failed on failed version 0.24.3, pass on fixed version 0.27.4
> [test] Add test for issue#6113

- test/sanity/issue6113-mac-create-crash/test.py
- Update method switch_to.window to switch_to_window
> [test] Update test.py to fix 6113 test

- src/api/nw_screen_api.cc
> DesktopCaptureMonitor: fix screens and windows can't be monitored at the same time.

- test/sanity/issue5980-aws-sdk-embedded-youtobe-video-crash/index.html
- test/sanity/issue5980-aws-sdk-embedded-youtobe-video-crash/index.js
- test/sanity/issue5980-aws-sdk-embedded-youtobe-video-crash/package.json
- test/sanity/issue5980-aws-sdk-embedded-youtobe-video-crash/test.py
- test/sanity/nw_util.py
- Add test for issue #5980
- This case is failed on failed version 0.23.5, pass on fixed version 0.27.4
> [test] Add test for issue#5980

- test/sanity/issue6099-AdSense-trouble/http-server.py
- test/sanity/issue6099-AdSense-trouble/iframe.html
- test/sanity/issue6099-AdSense-trouble/iframe.js
- test/sanity/issue6099-AdSense-trouble/index.js
- test/sanity/issue6099-AdSense-trouble/index.tpl
- test/sanity/issue6099-AdSense-trouble/package.json
- test/sanity/issue6099-AdSense-trouble/test.py
- Add test for issue #6099
- This case is failed on failed version 0.24.2, pass on fixed version 0.27.4
> [test] Add test for issue6099

- test/sanity/issue6136-nwjs-history-escapes-iframe/iframe-index.html
- test/sanity/issue6136-nwjs-history-escapes-iframe/iframe-second-page.html
- test/sanity/issue6136-nwjs-history-escapes-iframe/index.html
- test/sanity/issue6136-nwjs-history-escapes-iframe/package.json
- test/sanity/issue6136-nwjs-history-escapes-iframe/second-page.html
- test/sanity/issue6136-nwjs-history-escapes-iframe/test.py
- Add test for issue #6136
- This case is failed on failed version 0.24.4, pass on fixed version 0.28.0-beta1
> [test] Add test for isse6136

- test/sanity/issue5781-X-Frame-Options/http-server.py
- test/sanity/issue5781-X-Frame-Options/index.tpl
- test/sanity/issue5781-X-Frame-Options/package.json
- test/sanity/issue5781-X-Frame-Options/test.py
- Add test for issue #5781
- This case is passed on v0.21.2 and v0.27.4 after adding "nwfaketop"
> [test] Add test for issue5781

- test/sanity/issue6231-linux-websocket-more-than-2-connections/index.html
- test/sanity/issue6231-linux-websocket-more-than-2-connections/package.json
- test/sanity/issue6231-linux-websocket-more-than-2-connections/test.py
- Add test for issue #6231
- This case is failed on failed version 0.26.0, pass on v0.27.4
> [test] Add test for issue#6231

- test/sanity/issue6229-webview-executeScript/index.html
- test/sanity/issue6229-webview-executeScript/package.json
- test/sanity/issue6229-webview-executeScript/site.html
- test/sanity/issue6229-webview-executeScript/test.py
- Add test for isseu #6229
- This case is failed on failed version 0.26.0, pass on fixed version 0.27.4
> [test] Add test for issue6229

- test/sanity/issue6504-indexedDB-open-crash/main.html
- test/sanity/issue6504-indexedDB-open-crash/package.json
- test/sanity/issue6504-indexedDB-open-crash/test.py
- test/sanity/issue6504-indexedDB-open-crash/worker.js
- Add test for issue #6504
- This case is failed on v0.29.0, and passed on v0.29.1
> [test] Add test for issue6504

- test/sanity/issue6339-child-process-execSync-crash/index.html
- test/sanity/issue6339-child-process-execSync-crash/package.json
- test/sanity/issue6339-child-process-execSync-crash/test.py
- Add test for issue #6339
- This test is failed on v0.27.2, passed on v0.28.1
> [test] Add test for issue6339

- docs/References/Window.md
> [docs] Add the documentation for win.isAlwaysOnTop(#6536)

- docs/References/Window.md
- src/api/nw_current_window_internal.idl
- src/api/nw_window_api.cc
- src/api/nw_window_api.h
- src/api/nw_window_api_mac.mm
- src/resources/api_nw_window.js
I tested this on Mac, and it works!
Before:
After:
> Add support for nwWindow.setShadow(bool) on Mac

- test/sanity/issue4679-process-event-uncaughtException/index.html
- test/sanity/issue4679-process-event-uncaughtException/package.json
- test/sanity/issue4679-process-event-uncaughtException/test.py
- Add test for issue #4679
- This test is failed on v0.13.0, passed on v0.30.4
> [test] Add test for issue4679

- test/sanity/issue5093-window-size-match-package-json/index.html
- test/sanity/issue5093-window-size-match-package-json/package.json
- test/sanity/issue5093-window-size-match-package-json/test.py
- Add test for issue #5093
- This test is failed on v0.15.4, passed on v0.30.3
> [test] Add test for issue5093

- test/sanity/issue4993-window-resize-event-height/index.html
- test/sanity/issue4993-window-resize-event-height/package.json
- test/sanity/issue4993-window-resize-event-height/test.py
- Add test for issue #4993
- This test is failed on v0.15.4, passed on v0.30.4
> [test] Add test for issue4993

- docs/References/Window.md
Slight tweaks to the description to make it sound more natural. Fixed indentation in code example.
> Documentation: Window Closed Event

- test/sanity/issue6663-window-getPrinters-return-array/index.html
- test/sanity/issue6663-window-getPrinters-return-array/package.json
- test/sanity/issue6663-window-getPrinters-return-array/test.py
- Add test for issue #6663
- This test is failed on v0.31.0, passed on v0.31.1
> [test] Add test for issue6663

- src/api/nw_window_api_mac.mm
@rogerwang fix for mojave, please accept my pull request, also patch nw32
> [ProgressBar][MacOS] fix crash on Mojave, store progressIndicator using "AssociatedObject"

- test/sanity/issue5947-localStorage_getItem_url_crash/index.html
- test/sanity/issue5947-localStorage_getItem_url_crash/package.json
- test/sanity/issue5947-localStorage_getItem_url_crash/test.py
- Add this test for issue #5947
- This test is failed on v0.23.0, passed on v0.29.4
> [test] Add test for issue5947

- DEPS
https://github.com/nwjs/chromium.src/commit/72458df951740feb1485167308e8c4931bcf8748
> fix bug#6985: losing touchend event

- docs/References/MenuItem.md
> fix Typing error

- .github/ISSUE_TEMPLATE.md
I made a bunch of changes to the issue template based on what I have observed for the past week on how people have been writing up their bug reports. These changes are also a result what I've learnt triaging `nw-builder` issues. Let me know what you think!
> chore(docs): update issue template

- src/browser/nw_extensions_browser_hooks.cc
>  Fix #8039; Grey default icon in taskbar on Windows

- docs/References/Window.md
- src/resources/api_nw_newwin.js
- src/resources/api_nw_window.js
- test/sanity/window-setvisibleonallworkspaces/index.html
- test/sanity/window-setvisibleonallworkspaces/package.json
- test/sanity/window-setvisibleonallworkspaces/test.py
> fix win.canSetVisibleOnAllWorkspaces() return type
